# Exercicio 3

name: Fazendo Exercicio 3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Upando repositorio no runner
        uses: actions/checkout@v6.0.2

      - name: Configurando python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.13'

      - name: Instalando biblioteca build
        run: python3.13 -m pip install build
        
      - name: Gerando a build
        run: python3.13 -m build

      - name: Upando a build para artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: package
          path: dist/


  inspect:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Baixando artefato
        uses: actions/download-artifact@v7.0.0
        with:
          name: package

      - name: Listando pacote
        run: ls package

      - name: Validando nome da versão
        run: ls dist/*.whl
      
